version: 2
jobs:
  py2:
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: >
            docker build -t thomasjpfan/ubuntu-python-systemd:16.04-py2
            -f py2/Dockerfile .
      - run:
          name: Push to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
              docker push thomasjpfan/ubuntu-python-systemd:16.04-py2
            fi
  py3:
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: >
            docker build -t thomasjpfan/ubuntu-python-systemd:16.04-py3
            -f py3/Dockerfile .
      - run:
          name: Push to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
              docker push thomasjpfan/ubuntu-python-systemd:16.04-py3
            fi

workflows:
  version: 2
  build-both:
    jobs:
      - py2
      - py3