build_push: &build_push
  steps:
    - run:
        name: Build Docker Image
        command: |
          docker build -t $DOCKER_REPO:$CIRCLE_BRANCH -f python$PY_VERSION/Dockerfile .
    - run:
        name: Push to Docker Hub
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
            docker tag $DOCKER_REPO:$CIRCLE_BRANCH $DOCKER_REPO:16.04-py$PY_VERSION
            docker push $DOCKER_REPO:16.04-py$PY_VERSION
          fi

version: 2
jobs:
  py2:
    docker:
      - image: docker:17.12.0-ce-git
    environment:
      - DOCKER_REPO: thomasjpfan/ubuntu-python-systemd
      - PY_VERSION: 2
    <<: *build_push
  py3:
    docker:
      - image: docker:17.12.0-ce-git
    environment:
      - DOCKER_REPO: thomasjpfan/ubuntu-python-systemd
      - PY_VERSION: 3
    <<: *build_push

workflows:
  version: 2
  build-both:
    jobs:
      - py2
      - py3